using Microsoft.Extensions.DependencyInjection;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Retro.SimplePage.Swashbuckle;

/// <summary>
/// Extension methods for integrating pagination support into Swagger documentation using Swashbuckle.
/// </summary>
public static class PaginationSwaggerExtensions {

  /// <summary>
  /// Adds support for pagination parameters and attributes to the Swagger documentation.
  /// This method integrates pagination-related filters, such as parameters and schema definitions
  /// for pageable resources, into the Swagger documentation generated by Swashbuckle.
  /// </summary>
  /// <param name="options">The SwaggerGenOptions instance to configure with pagination support filters.</param>
  /// <returns>
  /// The modified SwaggerGenOptions instance, enabling pagination parameter and schema handling in Swagger documentation.
  /// </returns>
  public static SwaggerGenOptions AddPagination(this SwaggerGenOptions options) {
    options.AddOperationFilterInstance(new PageableParameterFilter());
    options.AddSchemaFilterInstance(new PagePropertyFilter());
    return options;
  }
  
}